name: Build and deploy ASP.Net Core app to Azure Web App - api-greencounty-blob

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 5 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore ./gc-blob-service/morris-azstorage-service/morris-azstorage-service.csproj

      - name: Build
        run: dotnet build ./gc-blob-service/morris-azstorage-service/morris-azstorage-service.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./gc-blob-service/morris-azstorage-service/morris-azstorage-service.csproj -c Release -f net5.0 -r win-x64 --no-self-contained -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v1
        with:
          app-name: 'api-greencounty-blob'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E7A459DD016A4E3B8116FAF5C06249D8 }}
          package: ./publish
